---

env:
  browser: true
  es6: true

overrides:
  -
    files:
      - 'index.ts'
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig.lint.json
      sourceType: module
